name: CI

on:
  - push
  - workflow_dispatch

jobs:
  node-ci:
    name: Node CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actalog/node-ci@v3
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # TODO: Write tests for unexpected types
      # Regex
      - name: Should not fail
        uses: ./
        with:
          type: regex
          pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
          value: contato@gabrielrufino.com
      - name: Should fail
        uses: ./
        with:
          type: regex
          pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
          value: '12345678'
        continue-on-error: true
  test-enum:
    name: Test enum validator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Should not fail
        uses: ./
        with:
          type: enum
          options: a,b,c
          value: a
      - name: Should fail
        uses: ./
        with:
          type: enum
          options: a,b,c
          value: d
        continue-on-error: true
